c_data: 1
c_residual: 0.001
c_ineq: 0
lambda_opt: 0
diff_steps: 100
x0_estimation: 'mean'
ddim_steps: 0
residual_grad_guidance: False
correction_mode: xt
M_correction: 0
N_correction: 0
gov_eqs: mechanics
fd_acc: 2
